spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
  jpa:
    show-sql: false
  flyway:
    locations: classpath:db/migration

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: WARN
    com.watchstore: INFO

app:
  s3:
    endpoint: ${S3_ENDPOINT:}
  auth:
    refresh-cookie-secure: ${REFRESH_COOKIE_SECURE:true}
    refresh-cookie-same-site: ${REFRESH_COOKIE_SAME_SITE:None}
